spring.application.name=workmax
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:6789/workmax
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.highlight_sql=true

spring.jpa.hibernate.ddl-auto=update
